/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rasyid andriansyah
 */
package view;

import java.util.logging.Level;
import java.util.logging.Logger;
import model.Tabledata;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import viewmodel.Game;
import viewmodel.Sound;
public class Menu extends javax.swing.JFrame {

    public Game game; // objek game
    private Tabledata texperiences; // data tabel
    public Clip audio; // backsound
    private String username; // username
    public Menu() {
       // konstruktor
        initComponents(); 
        this.username = ""; 
        try {
            this.texperiences = new Tabledata();
            Tabledata.setModel(texperiences.setTable());
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        // play sound di menu awal
        Sound bgm = new Sound();
        audio = bgm.playSound(this.audio, "codex.wav");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabledata = new javax.swing.JTable();
        btnPlay = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnQuit = new javax.swing.JButton();
        TFUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Keep Standing");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        Tabledata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        Tabledata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabledataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabledataMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(Tabledata);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 450, 240));

        btnPlay.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, -1, -1));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Input Username atau pilih dari tabel");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        btnQuit.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, -1, -1));

        TFUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(TFUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 280, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rasyid andriansyah\\Downloads\\tmd asset\\background copy.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 800, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        setSize(new java.awt.Dimension(814, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TFUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFUsernameActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
         this.dispose();
         System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
        if(this.username.length() == 0 && TFUsername.getText().length() != 0) {
            // jika nilai username masih kosong
            // dan text field TFUsername ada isinya
            this.username = TFUsername.getText();
        }
        if(TFUsername.getText().length() == 0 && this.username.length() == 0) {
            // jika text field kosong
            // dan nilai username masih kosong (tidak klik dari tabel)
            JOptionPane.showMessageDialog(this, "Username tidak boleh kosong!\nPilih user atau masukkan username baru.");
        } else {
            // sound new game
            Sound bgm = new Sound();
            bgm.stopSound(this.audio);
            
            // buat game baru
            game = new Game();
            GameWindow gw = new GameWindow(game);
            game.setUsername(this.username); // set username
            // cek apakah username sudah ada di database
            Tabledata temp = null;
            try {
                temp = new Tabledata();
            } catch (Exception ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
            temp.getDataTExperiences(this.username);
            int c = 0, tstanding = 0, tscore = 0;
            try {
                while(temp.getResult().next()){
                    // jika username sudah ada di database,
                    // ambil nilai standing dan score
                    tstanding = Integer.parseInt(temp.getResult().getString(3));
                    tscore = Integer.parseInt(temp.getResult().getString(4));
                    c++;
                }
            } catch (Exception ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
            // set score adapt dan fall di awal game
            if(c == 0){
                // jika user baru, adapt dan fall 0
                game.setNilai(0,0);
            } else {
                // jika user lama, adapt dan fall akumulasi
                game.setNilai(tstanding, tscore);
            }
            
            // game dimulai
            game.StartGame(gw);
            this.setVisible(false); // menu window dibuat invisible
            this.dispose(); // menu window di clear
        }
    }//GEN-LAST:event_btnPlayActionPerformed

    private void TabledataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabledataMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TabledataMouseEntered

    private void TabledataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabledataMouseClicked
        // TODO add your handling code here:
        // jika salah satu record dalam tabel di klik
        int row = Tabledata.getSelectedRow();
        // set username dengan username pada tabel yg di klik
        this.username = Tabledata.getModel().getValueAt(row, 0).toString();
        // set texfield berdasarkan username yg di klik
        TFUsername.setText(this.username);

    }//GEN-LAST:event_TabledataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFUsername;
    private javax.swing.JTable Tabledata;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnQuit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
